language: go
go:
- 1.7.1
notifications:
  slack:
    secure: HoVjD7ui2aWNc96BRQk6QZu0vjWvuu/4twdUYl4b4WxqgiqXmY3gFhyNsQ/RMjg92bkgot4mk/uPPfzMM7u/tJmdb7M4FxJ6iHHb9C+F9y59SrUhXIe3YNdJCi2o1E993zxI9yKA+v9fpOn2oQT+Nb2BCsQTeujG8zP7xzpvXasKNkiYam92Sdz38J9CJJB6NGAsnONVR1MDKfY9s3krS+VO2JmEtagB6qsPkuNJJuPyQgU9aSLnEqVEKJotTf6OxMmcH00Tv0Xq/pBdeY/9R4v/MCQTsJ/jg7POiLyyrh3tzDm3TsiFBaRVE8GgTM+PGz9MZKgbTqlY3JRHfFnLsEHGFVXL32gQ1qjWZv9pp7qTyzqephCXgSIGd2ya/q+K9W0JxaPCi7xpmbD72N54P9CnoL35jwWLwz/XTF9EJ5ygOBdJdm9rPnIczaMnC5CasU3QpxPIeQbQvtZULvp6pvVvwNQdq8DnOTrw/Gu/3t1vpCE1k5K8d5/d9ipGQH7hAU2F/djZo37ymi72WKjojkgC6NoM7+FmGczVI5zQmDEE022PL3CN+5WMdt7b3D2LLs0HfPdMFe2YJr6mq/0BjKBPDAn5/k3WUXUmJMNUvAhSP8+iJpxCeR8Tw8lY5hKJO5wbLYG1rTY5aeBvkGaroDDOw8LcCfKqDULqRGDVsRE=
